### ISSUE TITLE
Support lifecycle prefix

### ISSUE THREAD

**Issue by andrewharvey** [Booligoosh/sydneybikemap#1]
The [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) scheme is used along side the alternative `highway=construction` + `construction=*` scheme, and does have some usage: https://overpass-turbo.eu/s/1sOQ

Ideally these ways would be include for `proposed`, `planned`, `construction`.

**Comment by Booligoosh** [comment]
Thanks for checking this out and for all your good work on OSM! This is a good point - done now, going to implement #2 as well then push up so the tiles only need to rebuild once :slightly_smiling_face:
