### ISSUE TITLE
Exclude ways with mtb:scale or mtb:scale:imba

### ISSUE THREAD

**Issue by andrewharvey** [Booligoosh/sydneybikemap#2]
Some single trail MTB tracks are mapped as highway=cycleway which probably should be excluded for this map.

**Comment by Booligoosh** [comment]
This one is done now as well, nice catch! Unfortunately looks like it doesn't exclude all the MTB trails, but at least it's better than before. See this before/after for the north shore, you can see some trails get removed but there's still some around eg. in that area to the south-west of Hornsby.

Map state: https://sydneybikemap.ethan.link/#map=10.86/-33.7047/151.1385
Before:
![Screenshot 2023-03-24 at 15-26-42 SydneyBikeMap](https://user-images.githubusercontent.com/14034891/227424331-dfa8577a-749c-4690-9493-ef9dd54e7e12.png)

After:
![Screenshot 2023-03-24 at 15-26-51 SydneyBikeMap](https://user-images.githubusercontent.com/14034891/227424359-266d87e1-01a2-4e81-b6fc-3e46d1c417f4.png)

**Comment by andrewharvey** [comment]
Great, some are also mistaggings. Beyond that OSM doesn't have a good way to tag MTB trails, I worked on a proposal at https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:path%3Dmtb but it's a complex issue.
