### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MTRNord** [Booligoosh/sydneybikemap#5]
Hi,

First of all: Thanks a lot for making this AND documenting how to generate the tiles!

It seems to work great for other cities too. Which makes me wonder what the license of the software is :) I would love to host a version of this for my area as well. But currently there is no license defined :)

**Comment by Booligoosh** [comment]
Have licensed this as AGPL, that should allow you to host a version for your area and make any modifications as long as it's open-source!

**Comment by MTRNord** [comment]
Awesome! Thanks a lot!
